### ISSUE TITLE
color_coded 插件导致Vim 乱码

### ISSUE THREAD

**Issue by Arondight** [Arondight/profile#5]
一个悲伤的故事，目前还有待在其他机器上继续测试，另外观望下作者。

我感觉像是库的锅，这个现象，同YCM 缺失libtinfo 一个鸟样。

_(:з」∠)_

Ref [color_coded #118](https://github.com/jeaye/color_coded/issues/118)

**Comment by ZWindL** [comment]
看起来 Arch 用户都有这个问题？
我在 .color_coded 文件中加了 `-fcolor-diagnostics` 就不会乱了，但是依然没有高亮……

**Comment by ZWindL** [comment]
`:CCerror` 结果是 `/usr/include/wchar.h:39:11: fatal error: 'stdarg.h' file not found`

**Comment by Arondight** [comment]
```
$ pkgfile stdarg.h
core/gcc
extra/clang
………………
```

怎么会呀……

**Comment by ZWindL** [comment]
@Arondight 我也不知道了，不过你的终端乱码问题解决了吗？

**Comment by Arondight** [comment]
@ZWindL [我不用color_coded 了](https://github.com/Arondight/profile/commit/c8f321078c687ed539bf0e0d97150a8657a3b7c1#diff-4570ec26583846b94776a725fdc415cdL34)，等到这个问题没了再说……

**Comment by Arondight** [comment]
@ZWindL 已修复，见提交

**Comment by Arondight** [comment]
@ZWindL 之前那个`stdarg.h` 的东西你可以看下[color_coded #126](https://github.com/jeaye/color_coded/issues/126)

**Comment by ZWindL** [comment]
Thanx!
